page(
  '/',
  indexController.init
);
page(
  '/meditation/:meditation',
  meditationController.fetch,
  meditationController.init
);
page(
  '/journal/new',
  journalController.initEditor
);
page(
  '/journal/archive',
  journalController.template,
  journalController.getEntries
);
page.start();
